### ISSUE TITLE
using a bad organization or game gives an opaque error message

### ISSUE THREAD

**Issue by neilsarkar** [vaguevoid/actions#9]
e.g. https://github.com/vaguevoid/thingmaker/actions/runs/9927917894/job/27423504126 or any of the other runs around that time

I think these failed because I was using orgs I didn't have access to and/or nonexistent orgs and games. it would be helpful to 404 or 401 on the org and game to allow for easier debugging

**Comment by jakesgordon** [comment]
Should be a bit better now, If the upload returns a 404 (which happens for either unknown or unauthorized organization or game) a slightly better message is now displayed

![better-error-message](https://github.com/user-attachments/assets/687d4ab7-57fc-45d8-943a-a2110d36f503)
